# Generated by Django 3.1.3 on 2020-11-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.IntegerField()),
                ('nameProduct', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('discontinued', models.BooleanField()),
                ('idCategory', models.IntegerField()),
            ],
        ),
    ]
