# Generated by Django 3.1.3 on 2020-11-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='idProduct',
        ),
    ]
