# Generated by Django 3.1.3 on 2020-11-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0003_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='idCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_api.categories'),
        ),
    ]
