# Generated by Django 3.1.3 on 2020-11-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0005_auto_20201118_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCustomer', models.CharField(max_length=255)),
                ('addCustomer', models.CharField(max_length=255)),
                ('emailCustomer', models.CharField(max_length=255)),
                ('phoneCustomer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateTimeField()),
                ('shippedDate', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_api.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_api.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_api.products')),
            ],
        ),
    ]
